version: "3.9" # optional since v1.27.0
services:
  bd:
    image: "mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04"
    container_name: bd_clientes
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Upt.2022
    volumes:
      - ./db:/tmp
  api:
    build: ClienteAPI/. # build the Docker image
    container_name: api_clientes
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__ClienteDB=Server=bd_clientes;Database=BD_CLIENTES;User Id=sa;Password=Upt.2022;TrustServerCertificate=true
    depends_on:
      - bd